/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ejercicio2;

/**
 *
 * @author Vespertino
 */
public class Gui extends javax.swing.JFrame {

    private int minutos, horas, segundos /**
             * Creates new form Gui
             */

    public Gui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelContenedor = new javax.swing.JPanel();
        jPanelReloj = new javax.swing.JPanel();
        jLabelDecenaHora = new javax.swing.JLabel();
        jLabelUnidadHora = new javax.swing.JLabel();
        jLabelSeparador1 = new javax.swing.JLabel();
        jLabelDecenaMinuto = new javax.swing.JLabel();
        jLabelUnidadMinuto = new javax.swing.JLabel();
        jLabelSeparador2 = new javax.swing.JLabel();
        jLabelDecenaSegundo = new javax.swing.JLabel();
        jLabelUnidadSegundo = new javax.swing.JLabel();
        jPanelBoton = new javax.swing.JPanel();
        jButtonIniciar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelContenedor.setLayout(new java.awt.BorderLayout());

        jLabelDecenaHora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ejercicio2img/0.gif"))); // NOI18N
        jPanelReloj.add(jLabelDecenaHora);

        jLabelUnidadHora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ejercicio2img/0.gif"))); // NOI18N
        jPanelReloj.add(jLabelUnidadHora);

        jLabelSeparador1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ejercicio2img/separador.gif"))); // NOI18N
        jPanelReloj.add(jLabelSeparador1);
        jLabelSeparador1.getAccessibleContext().setAccessibleName("");

        jLabelDecenaMinuto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ejercicio2img/0.gif"))); // NOI18N
        jPanelReloj.add(jLabelDecenaMinuto);

        jLabelUnidadMinuto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ejercicio2img/0.gif"))); // NOI18N
        jPanelReloj.add(jLabelUnidadMinuto);

        jLabelSeparador2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ejercicio2img/separador.gif"))); // NOI18N
        jPanelReloj.add(jLabelSeparador2);
        jLabelSeparador2.getAccessibleContext().setAccessibleName("");

        jLabelDecenaSegundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ejercicio2img/0.gif"))); // NOI18N
        jPanelReloj.add(jLabelDecenaSegundo);

        jLabelUnidadSegundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ejercicio2img/0.gif"))); // NOI18N
        jPanelReloj.add(jLabelUnidadSegundo);

        jPanelContenedor.add(jPanelReloj, java.awt.BorderLayout.CENTER);

        jButtonIniciar.setText("Iniciar");
        jButtonIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIniciarActionPerformed(evt);
            }
        });
        jPanelBoton.add(jButtonIniciar);

        jPanelContenedor.add(jPanelBoton, java.awt.BorderLayout.SOUTH);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelContenedor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIniciarActionPerformed
        Thread t = new (Thread)
    }//GEN-LAST:event_jButtonIniciarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonIniciar;
    private javax.swing.JLabel jLabelDecenaHora;
    private javax.swing.JLabel jLabelDecenaMinuto;
    private javax.swing.JLabel jLabelDecenaSegundo;
    private javax.swing.JLabel jLabelSeparador1;
    private javax.swing.JLabel jLabelSeparador2;
    private javax.swing.JLabel jLabelUnidadHora;
    private javax.swing.JLabel jLabelUnidadMinuto;
    private javax.swing.JLabel jLabelUnidadSegundo;
    private javax.swing.JPanel jPanelBoton;
    private javax.swing.JPanel jPanelContenedor;
    private javax.swing.JPanel jPanelReloj;
    // End of variables declaration//GEN-END:variables

    void suma() { //Suma a los labes
        if (segundos != 59) {
            segundos++;
        } else {
            segundos = 0;
            if (minutos != 59) {
                minutos++;
            } else {
                minutos = 0;
                if (horas != 23) {
                    horas++;
                } else {
                    horas = 0;
                }
            }
        }
        muestraDisplay();

    }

    private void muestraDisplay() {
           int su,sd,mu,md,hu,hd;
           
           su = segundos %10;
           sd = segundos/ 10;
           
           mu = minutos %10;
           md = minutos / 10;
           
           hu = horas %10;
           hd = horas / 10;
           
           jLa
    }
}
